#!/bin/bash

if [ ! -e _tmp ];
then
    mkdir _tmp
fi

# Obtain and find our kernel source
cd _tmp
apt-get source linux
kernel=$(basename `find . -maxdepth 1 -type d -name "linux-3*"`)
cd ..

# Copy config to kernel source dir
cp kernel/config _tmp/$kernel/.config 

# Build kernel
cd _tmp/$kernel
make deb-pkg -j4 LOCALVERSION=-seedian KDEB_PKGVERSION=$(make kernelversion)-1
