#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

groups="sudo"

# add a seed user account
if ! $ROOTCMD getent passwd seed ; then
    $ROOTCMD adduser --disabled-login --gecos "initial seed user" seed
    $ROOTCMD usermod -p "$ROOTPW" seed
    for g in $groups; do
        $ROOTCMD adduser seed $g
    done
fi

# enable NTP
# We can't just use `timedatectl set-ntp true` because dbus may not be ready.
$ROOTCMD systemctl enable systemd-timesyncd

ainsl -a /etc/puppetlabs/puppet/puppet.conf "^server=${PUPPET_SERVER}$"
ainsl -a /etc/puppetlabs/puppet/puppet.conf "^environment=${PUPPET_ENVIRONMENT:-production}$"
